<template>
  <the-content :title="title">
    <h2>Privacy Policy</h2>
    <p>
      Last updated: February 25, 2021 This Privacy Policy describes Our policies
      and procedures on the collection, use and disclosure of Your information
      when You use the Service and tells You about Your privacy rights and how
      the law protects You. We use Your Personal data to provide and improve the
      Service. By using the Service, You agree to the collection and use of
      information in accordance with this Privacy Policy.
    </p>
    <h2>Interpretation and Definitions</h2>

    <h3>Interpretation</h3>
    <p>
      The words of which the initial letter is capitalized have meanings defined
      under the following conditions. The following definitions shall have the
      same meaning regardless of whether they appear in singular or in plural.
    </p>
    <h2>Definitions</h2>

    <h3>For the purposes of this Privacy Policy</h3>

    <ul>
      <li>
        Account means a unique account created for You to access our Service or
        parts of our Service.
      </li>
      <li>
        Affiliate means an entity that controls, is controlled by or is under
        common control with a party, where "control" means ownership of 50% or
        more of the shares, equity interest or other securities entitled to vote
        for election of directors or other managing authority.
      </li>
      <li>
        Application means the software program provided by the Company
        downloaded by You on any electronic device, named lodgingnbed
      </li>
      <li>
        Company (referred to as either "the Company", "We", "Us" or "Our" in
        this Agreement) refers to lodgingnbed.
      </li>
      <li>Country refers to: Andorra</li>
      <li>
        Device means any device that can access the Service such as a computer,
        a cellphone or a digital tablet.
      </li>
      <li>
        Personal Data is any information that relates to an identified or
        identifiable individual.
      </li>
      <li>Service refers to the Application.</li>
      <li>
        Service Provider means any natural or legal person who processes the
        data on behalf of the Company. It refers to third-party companies or
        individuals employed by the Company to facilitate the Service, to
        provide the Service on behalf of the Company, to perform services
        related to the Service or to assist the Company in analyzing how the
        Service is used.
      </li>
      <li>
        Third-party Social Media Service refers to any website or any social
        network website through which a User can log in or create an account to
        use the Service.
      </li>
      <li>
        Usage Data refers to data collected automatically, either generated by
        the use of the Service or from the Service infrastructure itself (for
        example, the duration of a page visit).
      </li>
      <li>
        You means the individual accessing or using the Service, or the company,
        or other legal entity on behalf of which such individual is accessing or
        using the Service, as applicable.
      </li>
    </ul>
    <h2>Collecting and Using Your Personal Data</h2>
    <h3>Types of Data Collected</h3>
    <h4>Personal Data</h4>
    <p>
      While using Our Service, We may ask You to provide Us with certain
      personally identifiable information that can be used to contact or
      identify You. Personally identifiable information may include, but is not
      limited to: Usage Data
    </p>
    <h4>Usage Data</h4>
    <p>
      Usage Data is collected automatically when using the Service. Usage Data
      may include information such as Your Device's Internet Protocol address
      (e.g. IP address), browser type, browser version, the pages of our Service
      that You visit, the time and date of Your visit, the time spent on those
      pages, unique device identifiers and other diagnostic data. When You
      access the Service by or through a mobile device, We may collect certain
      information automatically, including, but not limited to, the type of
      mobile device You use, Your mobile device unique ID, the IP address of
      Your mobile device, Your mobile operating system, the type of mobile
      Internet browser You use, unique device identifiers and other diagnostic
      data.
    </p>

    <p>
      We may also collect information that Your browser sends whenever You visit
      our Service or when You access the Service by or through a mobile device.
    </p>
    <h2>Information Collected</h2>
    <p>
      while Using the Application While using Our Application, in order to
      provide features of Our Application, We may collect, with Your prior
      permission: Information regarding your location We use this information to
      provide features of Our Service, to improve and customize Our Service. The
      information may be uploaded to the Company's servers and/or a Service
      Provider's server or it may be simply stored on Your device. You can
      enable or disable access to this information at any time, through Your
      Device settings.
    </p>

    <h2>Retention of Your Personal Data</h2>
    <p>
      The Company will retain Your Personal Data only for as long as is
      necessary for the purposes set out in this Privacy Policy. We will retain
      and use Your Personal Data to the extent necessary to comply with our
      legal obligations (for example, if we are required to retain your data to
      comply with applicable laws), resolve disputes, and enforce our legal
      agreements and policies. The Company will also retain Usage Data for
      internal analysis purposes. Usage Data is generally retained for a shorter
      period of time, except when this data is used to strengthen the security
      or to improve the functionality of Our Service, or We are legally
      obligated to retain this data for longer time periods.
    </p>
    <h2>Transfer of Your Personal Data</h2>
    <p>
      Your information, including Personal Data, is processed at the Company's
      operating offices and in any other places where the parties involved in
      the processing are located. It means that this information may be
      transferred to — and maintained on — computers located outside of Your
      state, province, country or other governmental jurisdiction where the data
      protection laws may differ than those from Your jurisdiction. Your consent
      to this Privacy Policy followed by Your submission of such information
      represents Your agreement to that transfer. The Company will take all
      steps reasonably necessary to ensure that Your data is treated securely
      and in accordance with this Privacy Policy and no transfer of Your
      Personal Data will take place to an organization or a country unless there
      are adequate controls in place including the security of Your data and
      other personal information.
    </p>
    <h2>Disclosure of Your Personal Data</h2>

    <h3>Business Transactions</h3>
    <p>
      If the Company is involved in a merger, acquisition or asset sale, Your
      Personal Data may be transferred. We will provide notice before Your
      Personal Data is transferred and becomes subject to a different Privacy
      Policy.
    </p>
    <h3>Law enforcement</h3>
    <p>
      Under certain circumstances, the Company may be required to disclose Your
      Personal Data if required to do so by law or in response to valid requests
      by public authorities (e.g. a court or a government agency).
    </p>
    <h3>Other legal requirements</h3>
    <p>
      The Company may disclose Your Personal Data in the good faith belief that
      such action is necessary to: Comply with a legal obligation Protect and
      defend the rights or property of the Company Prevent or investigate
      possible wrongdoing in connection with the Service Protect the personal
      safety of Users of the Service or the public Protect against legal
      liability Security of Your Personal Data The security of Your Personal
      Data is important to Us, but remember that no method of transmission over
      the Internet, or method of electronic storage is 100% secure. While We
      strive to use commercially acceptable means to protect Your Personal Data,
      We cannot guarantee its absolute security.
    </p>
    <h3>Children's Privacy</h3>
    <p>
      Our Service does not address anyone under the age of 13. We do not
      knowingly collect personally identifiable information from anyone under
      the age of 13. If You are a parent or guardian and You are aware that Your
      child has provided Us with Personal Data, please contact Us. If We become
      aware that We have collected Personal Data from anyone under the age of 13
      without verification of parental consent, We take steps to remove that
      information from Our servers. If We need to rely on consent as a legal
      basis for processing Your information and Your country requires consent
      from a parent, We may require Your parent's consent before We collect and
      use that information.
    </p>
    <h3>Links to Other Websites</h3>
    <p>
      Our Service may contain links to other websites that are not operated by
      Us. If You click on a third party link, You will be directed to that third
      party's site. We strongly advise You to review the Privacy Policy of every
      site You visit. We have no control over and assume no responsibility for
      the content, privacy policies or practices of any third party sites or
      services.
    </p>
    <h3>Contact Us</h3>
    <p>
      If you have any questions about this Privacy Policy, You can contact us:
      By email: support@lodgingnbed.ma LodgingNbed, Tangier 90300, Moulay
      Youssef, N12 APP 108
    </p>
  </the-content>
</template>

<script>
import { ref } from "vue";
export default {
  setup() {
    const title = ref("");
    return {
      title,
    };
  },
};
</script>

<style lang="scss" scoped>
h2,
h3 {
  color: var(--color-primary-dark);
  margin-bottom: 3rem;
}

p,
ul {
  line-height: 160%;
  margin: 0 0 5rem 0;
}
</style>
